version: "3.9"

services:
  backend:
    build: ./resumatch-backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - ./resumatch-backend/.env
    volumes:
      - ./resumatch-backend:/app
  frontend:
    build: ./resumatcher-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    volumes:
      - ./resumatcher-frontend:/app
    depends_on:
      - backend
    # command: sh -c "npm install && npm run dev -- --host